### ISSUE TITLE
Nice approach but it missing imports evan after installing brew install libgit2 - Xcode12

### ISSUE THREAD

**Issue by doozMen** [SwiftDocOrg/Git#1]
when I change it to an absolute path it works.

I think you should add https://developer.apple.com/documentation/swift_packages/cxxsetting/3112674-headersearchpath

But not sure how

**Comment by mattt** [comment]
As of #2, CI is passing with Xcode 12 and Swift 5.3 on macOS Catalina. I don't have any guesses for why it's not working on your machine, though...
